allow run-when-changed to execute a command, instead of just a script

diff --git a/bin/run-when-changed b/bin/run-when-changed
--- a/bin/run-when-changed
+++ b/bin/run-when-changed
@@ -27,10 +27,10 @@ fi
 command=$1
 shift 1
 
-if [ ! -f $test_file ]; then
-  echo "Could not find file to run: $test_file"
-  exit 1
-fi
+# if [ ! -f $test_file ]; then
+#   echo "Could not find file to run: $test_file"
+#   exit 1
+# fi
 
 RUN_PID=
 
